### ISSUE TITLE
Send to X Controlnet does not work

### ISSUE THREAD

**Issue by IkariDevGIT** [AlUlkesh/stable-diffusion-webui-images-browser#149] opened 2023-04-30 11:16 UTC
no error in webui console,

system: Windows 10
browser: Firefox 112.0.2 (64-Bit)
Webui: [Vladmandic´s auto1111 fork](https://github.com/vladmandic/automatic) (Version: 67c39202 Sun Apr 30 11:16:58 2023 +0900)
Python: 3.10.6

javascript error:
```
Uncaught (in promise) TypeError: tabNavButton is undefined
    image_browser_gototab image_browser.js:220
    image_browser_controlnet_send image_browser.js:293
    image_browser_controlnet_send_txt2img image_browser.js:377
    anonymous Blocks.5efe22d4.js line 75 > AsyncFunction:3
    ze Blocks.5efe22d4.js:76
    to Blocks.5efe22d4.js:76
    zr index.37b24c07.js:4
    zr index.37b24c07.js:4
    _ Button.svelte:12
    zr index.37b24c07.js:4
    zr index.37b24c07.js:4
    c Button.svelte:11
    Le index.37b24c07.js:1
    m Button.svelte:16
    ue index.37b24c07.js:4
    m Button.svelte:21
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Row.svelte:11
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Column.svelte:14
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Row.svelte:11
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
[image_browser.js:220:5](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
    image_browser_controlnet_send image_browser.js:374
    AsyncFunctionThrow self-hosted:814
    (Async: async)
    image_browser_controlnet_send_txt2img image_browser.js:377
    anonymous Blocks.5efe22d4.js line 75 > AsyncFunction:3
    ze Blocks.5efe22d4.js:76
    to Blocks.5efe22d4.js:76
    zr index.37b24c07.js:4
    forEach self-hosted:203
    zr index.37b24c07.js:4
    _ Button.svelte:12
    zr index.37b24c07.js:4
    forEach self-hosted:203
    zr index.37b24c07.js:4
    c Button.svelte:11
    (Async: EventListener.handleEvent)
    Le index.37b24c07.js:1
    m Button.svelte:16
    ue index.37b24c07.js:4
    m Button.svelte:21
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Row.svelte:11
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Column.svelte:14
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Row.svelte:11
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
```

**Comment by IkariDevGIT** [comment] 2023-04-30 11:23
here are the logs made by maintenance mode:

```
2023-04-30-11-22-04 image_browser.js: image_browser_activate_controls:end
2023-04-30-11-22-16 image_browser.js: image_browser_turnpage:start
2023-04-30-11-22-16 image_browser.js: image_browser_turnpage:end
2023-04-30-11-22-17 image_browser.js: image_browser_click_image:start
2023-04-30-11-22-17 image_browser.js: image_browser_lock:start
2023-04-30-11-22-17 image_browser.js: image_browser_lock:end
2023-04-30-11-22-17 image_browser.js: image_browser_current_tab:start
2023-04-30-11-22-17 image_browser.js: image_browser_current_tab:end
2023-04-30-11-22-17 image_browser.js: image_browser_unlock:start
2023-04-30-11-22-17 image_browser.js: image_browser_unlock:end
2023-04-30-11-22-17 image_browser.js: image_browser_get_current_img:start
2023-04-30-11-22-17 image_browser.js: image_browser_lock:start
2023-04-30-11-22-17 image_browser.js: image_browser_lock:end
2023-04-30-11-22-17 image_browser.js: image_browser_click_image:end
2023-04-30-11-22-17 image_browser.js: image_browser_unlock:start
2023-04-30-11-22-17 image_browser.js: image_browser_unlock:end
2023-04-30-11-22-17 image_browser.js: image_browser_get_current_img:end
2023-04-30-11-22-23 image_browser.js: image_browser_controlnet_send:start
2023-04-30-11-22-23 image_browser.js: image_browser_get_image_for_ext:start
2023-04-30-11-22-23 image_browser.js: image_browser_get_image_for_ext:end
2023-04-30-11-22-24 image_browser.js: image_browser_gototab:start
2023-04-30-11-22-24 image_browser.js: image_browser_lock:start
2023-04-30-11-22-24 image_browser.js: image_browser_lock:end
2023-04-30-11-22-27 image_browser.js: btnClickHandler:start
2023-04-30-11-22-27 image_browser.js: btnClickHandler:end
```

**Comment by IkariDevGIT** [comment] 2023-04-30 13:14
+ now i cant send anything, for example: "send to text2img" or something does not work. here is the webui error(+this error also pops up with "send controllnet to txt2img"):

```
Traceback (most recent call last):
  File "D:\-automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\-automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\-automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 332
```

**Comment by IkariDevGIT** [comment] 2023-04-30 13:26
I also should note that there is a warning by the extension about something with MariaDB threading. but idk why but I get that error to show up again, I only remember this: "something with MariaDB, IDs, and threading". it said something like "can't open new mariadb in new thread id 71238 blabla", this may be wrong as my memory is very faded out!

and I think it has something to do with the database thing because a db is used in the code for sending the metadata to txt2img, img2img, ...

![grafik](https://user-images.githubusercontent.com/90197782/235355180-a7814699-f18a-47e3-8078-8a423fa7d471.png)

**Comment by AlUlkesh** [comment] 2023-04-30 17:44
Unfortunately I can't reproduce this.

No idea what a MariaDB might be...

I had the KeyError before when I reused a browser session (with Reload UI or similar).

Do you get the error when you restart webui and open a new tab to try it out?

**Comment by IkariDevGIT** [comment] 2023-04-30 18:20
yes, complete system restart did not work too.

**Comment by AlUlkesh** [comment] 2023-04-30 18:53
Ok, can you get me a log file, as described here: #130 
Please note the last line about Vlad's fork.

**Comment by IkariDevGIT** [comment] 2023-04-30 19:04
i only get this in when doing the vladmandic thing: https://pastebin.com/67Kknwjr
and without the restart debug thing: I already sent it in here before

**Comment by IkariDevGIT** [comment] 2023-04-30 19:05
if i look manually inside the firefox javascript console I get this error:

Uncaught (in promise) TypeError: tabNavButton is undefined
    image_browser_gototab http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728:220

**Comment by IkariDevGIT** [comment] 2023-04-30 19:07
and now i got this:

Uncaught (in promise) Error: Still locked after 30 seconds. Please Reload UI.
    image_browser_lock image_browser.js:76
    image_browser_gototab image_browser.js:208
    image_browser_controlnet_send image_browser.js:293
    image_browser_controlnet_send_txt2img image_browser.js:377
    anonymous Blocks.5efe22d4.js line 75 > AsyncFunction:3
    ze Blocks.5efe22d4.js:76
    to Blocks.5efe22d4.js:76
    zr index.37b24c07.js:4
    zr index.37b24c07.js:4
    _ Button.svelte:12
    zr index.37b24c07.js:4
    zr index.37b24c07.js:4
    c Button.svelte:11
image_browser.js:76:19

**Comment by IkariDevGIT** [comment] 2023-04-30 19:14
remember when i was talking about mariadb? yea, that message appeared again

```SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 8620 and this is thread id 21028.```

**Comment by AlUlkesh** [comment] 2023-04-30 20:07
> mariadb

Close enough 😆 

That's weird. I take it you don't have multiple instances of webui running? Or doing things in multiple image browser tabs at the same time?

**Comment by IkariDevGIT** [comment] 2023-04-30 21:00
no

**Comment by IkariDevGIT** [comment] 2023-04-30 21:00
bruhh, i swear there was mariadb before

**Comment by AlUlkesh** [comment] 2023-05-01 12:01
Okay, let's start over. I see too many error messages and am not sure about the order. I suspect many are just follow-up errors of the original error.

When you restart webui and open a new tab and proceed to try and send to controlnet, what are the outputs on the javascript console. Correct order and complete please. Thanks.

**Comment by IkariDevGIT** [comment] 2023-05-01 17:34
here is the raw firefox console output:

```
task active: task(z8pfx3abt5qk8iw) [progressbar.js:67:13](http://127.0.0.1:7860/file=javascript/progressbar.js?1682434382.33744)
task end:    task(z8pfx3abt5qk8iw) [progressbar.js:75:17](http://127.0.0.1:7860/file=javascript/progressbar.js?1682434382.33744)
image_browser_turnpage:start [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_turnpage:end [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_click_image:start [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_lock:start [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_lock:end [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_current_tab:start [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_current_tab:end [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_unlock:start [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_unlock:end [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_get_current_img:start [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_lock:start [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_lock:end [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_click_image:end [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_unlock:start [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_unlock:end [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_get_current_img:end [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_controlnet_send:start [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_get_image_for_ext:start [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_get_image_for_ext:end [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_gototab:start [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_lock:start [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
image_browser_lock:end [image_browser.js:442:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728)
Uncaught (in promise) TypeError: tabNavButton is undefined
    image_browser_gototab http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682350530.1015728:220
```

**Comment by IkariDevGIT** [comment] 2023-05-01 17:51
the same error when using Chrome instead of Firefox:

```
[dumpunet] initialized
index-f85c2dbf.js:169 Array(1)
image_browser.js?1682350530.1015728:442 image_browser_activate_controls:end
emptyStartup-6ee8cfd4.js:1 Proxy(Object)
image_browser.js?1682350530.1015728:442 image_browser_turnpage:start
image_browser.js?1682350530.1015728:442 image_browser_turnpage:end
image_browser.js?1682350530.1015728:442 image_browser_click_image:start
image_browser.js?1682350530.1015728:442 image_browser_lock:start
image_browser.js?1682350530.1015728:442 image_browser_lock:end
image_browser.js?1682350530.1015728:442 image_browser_current_tab:start
image_browser.js?1682350530.1015728:442 image_browser_current_tab:end
image_browser.js?1682350530.1015728:442 image_browser_unlock:start
image_browser.js?1682350530.1015728:442 image_browser_unlock:end
image_browser.js?1682350530.1015728:442 image_browser_get_current_img:start
image_browser.js?1682350530.1015728:442 image_browser_lock:start
image_browser.js?1682350530.1015728:442 image_browser_lock:end
image_browser.js?1682350530.1015728:442 image_browser_click_image:end
image_browser.js?1682350530.1015728:442 image_browser_unlock:start
image_browser.js?1682350530.1015728:442 image_browser_unlock:end
image_browser.js?1682350530.1015728:442 image_browser_get_current_img:end
image_browser.js?1682350530.1015728:442 image_browser_controlnet_send:start
image_browser.js?1682350530.1015728:442 image_browser_get_image_for_ext:start
image_browser.js?1682350530.1015728:442 image_browser_get_image_for_ext:end
image_browser.js?1682350530.1015728:442 image_browser_gototab:start
image_browser.js?1682350530.1015728:442 image_browser_lock:start
image_browser.js?1682350530.1015728:442 image_browser_lock:end
image_browser.js?1682350530.1015728:220 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'click')
    at image_browser_gototab (image_browser.js?1682350530.1015728:220:18)
    at async image_browser_controlnet_send (image_browser.js?1682350530.1015728:293:5)
```

the same error when using Chrome instead of Firefox.

**Comment by AlUlkesh** [comment] 2023-05-01 18:00
Thanks. I found it. The issue is that Vlad's fork by default uses other tab names, like `From Text` instead of `txt2img`. I'm gonna see if I can use ids instead of names.

**Comment by IkariDevGIT** [comment] 2023-05-01 20:04
when will the update be out?

**Comment by AlUlkesh** [comment] 2023-05-01 21:28
I'm currently working on it. Shouldn't be too long.

**Comment by AlUlkesh** [comment] 2023-05-01 21:51
Ok, you can try it out now.

**Comment by IkariDevGIT** [comment] 2023-05-02 17:44
works a little bit, it basically sends the image, but not the metadata(for example: the checkboxes and sliders). Here is the Javascript console log:

```
[dumpunet] initialized [layerinfo.js:139:13](http://127.0.0.1:7860/file=extensions/stable-diffusion-webui-dumpunet/javascript/layerinfo.js?1682859792.5133865)
Array [ Proxy ]
[index-62215747.js:169:3745](http://127.0.0.1:7860/infinite_image_browsing/fe-static/assets/index-62215747.js)
Proxy { <target>: {…}, <handler>: {…} }
[emptyStartup-0577391b.js:1:2847](http://127.0.0.1:7860/infinite_image_browsing/fe-static/assets/emptyStartup-0577391b.js)
image_browser_turnpage:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_turnpage:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_click_image:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_lock:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_lock:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_current_tab:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_current_tab:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_unlock:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_unlock:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_get_current_img:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_lock:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_lock:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_click_image:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_unlock:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_unlock:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_get_current_img:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_controlnet_send:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_get_image_for_ext:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_get_image_for_ext:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_gototab:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_lock:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_lock:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_unlock:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_unlock:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_gototab:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_webui_current_tab:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_webui_current_tab:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_controlnet_send:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_controlnet_send:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_get_image_for_ext:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_get_image_for_ext:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_gototab:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_lock:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_lock:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_unlock:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_unlock:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_gototab:end [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
image_browser_webui_current_tab:start [image_browser.js:457:20](http://127.0.0.1:7860/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1683029419.1442304)
```

**Comment by AlUlkesh** [comment] 2023-05-02 18:01
It has never done that.

If it sends the image, the bug is fixed. I'll close this issue.

If you want it to send more than the image please open a new enhancement issue with more details.

**Closed by AlUlkesh** 2023-05-02 18:01 UTC
Labels: bug
