### ISSUE TITLE
Feature Request: Send ControlNet picture metadata

### ISSUE THREAD

**Issue by IkariDevGIT** [AlUlkesh/stable-diffusion-webui-images-browser#153] opened 2023-05-02 18:26 UTC
I would like that the button that sends the image to controlNet to also send the pictures metadata(of controlnet) to the specified tab

**Comment by AlUlkesh** [comment] 2023-05-02 19:53
But how would that "metadata" be saved in that image in the first place?

My understanding is:
- txt2img: You have the controlnet "guidance" image and then the generated image
- img2img: You have the controlnet "guidance" image, the img2img source image and then the generated image

pnginfo is always only added to the generated image, not the guidance image.

Image Browser sends the guidance image to controlnet.

Perhaps there's a feature I am not aware of?

**Comment by AlUlkesh** [comment] 2023-05-03 15:16
But on which image is that added? The guidance image or the generated image?

**Comment by IkariDevGIT** [comment] 2023-05-03 15:50
what? It would make no sense to add it to the guidance image. i don't think you understand what I request as a feature, so I'm gonna explain it again:

I want a feature which picks out the metadata of the picture in the output txt2img folder(which of course is the generated images), and send the parameters(metadata)  saved in the image to the selected controlNet(instead of sending the image to controlnet, which it currently does)

**Comment by AlUlkesh** [comment] 2023-05-03 18:57
Well, I'm glad we agree, that this wouldn't make sense with the guidance image.

I would have expected this to work "out-of-the-box" when you send an image to txt2img or img2img, like it works for every other parameter.

However that does not seem to be the case. I've just asked for more info on the controlnet repo.

**Comment by IkariDevGIT** [comment] 2023-05-05 13:09
any updates?

**Comment by AlUlkesh** [comment] 2023-05-05 15:24
No, no answer 😞 
Guess, I'll have to check myself how their code expects other scripts to access it. There is after all a setting like that.

**Comment by IkariDevGIT** [comment] 2023-05-05 15:31
sorry to burden you with this task, i would help if I would know how tf gradio works.(cant you just use the code like in send to X To Img?)

**Comment by IkariDevGIT** [comment] 2023-05-06 11:13
and? got some news?

**Comment by AlUlkesh** [comment] 2023-05-06 11:21
No. No response yet.

**Comment by AlUlkesh** [comment] 2023-05-06 11:33
BTW if you want to help, what you could do is the following. This code needs to be extended:
```
            (enabled, f"{tabname} Enabled"),
            (module, f"{tabname} Preprocessor"),
            (model, f"{tabname} Model"),
            (weight, f"{tabname} Weight"),
            (guidance_start, f"{tabname} Guidance Start"),
            (guidance_end, f"{tabname} Guidance End"),
```
So, if you could find all the missing items, that would be great.

The right name in a line is the name, as it appears in the pnginfo.

The left name is how it's refered to in the code: 
https://github.com/Mikubill/sd-webui-controlnet/blob/11d33e181523c509c235d1278e94ce61d2d8d366/scripts/controlnet.py#L858

**Comment by IkariDevGIT** [comment] 2023-05-06 12:15
hmm, i really dont know how.. im not good at programming. and how would we extend the code of another extension?

**Comment by AlUlkesh** [comment] 2023-05-06 14:42
We would put in a Pull Request on their repo, asking for the code to be merged.

It would help already, if you collected all the field names, as they are called on the UI.

**Comment by IkariDevGIT** [comment] 2023-05-11 19:46
any news?

**Comment by siramods** [comment] 2023-09-29 22:29
Just to leave my two cents, I think this to be a **very** important and missing feature, ControlNet tuning gets quite laborious, and currently "PNG info" tab does not send the parameters to ControlNet either, so we are stuck with restoring countless values reading the meta and typing it by hand. In addition to what was commented before, its badly needed that there is an option where _only_ the CN data is sent, not the prompt, etc, because those settings are often used as templates for specific types of jobs. The "send image to CN" is welcomed, thank you!

**Comment by AlUlkesh** [comment] 2023-09-30 06:50
Yes, I'll look back into it. Since I last I looked, controlnet has had massive changes. Perhaps it is easier possible now.

**Comment by AlUlkesh** [comment] 2023-10-01 15:02
@siramods:

Well, here's a twist. After throughly debugging through this whole construct I realized, controlnet does in fact support this by now.

It's just not working for me (and I suspect for you), because another extension is adding pnginfo in a format that a1111 can't handle.

For example, my image info looks like this:

```
beautiful eye closeup <lora:epiCRealismHelper:1>
Negative prompt:  easynegative
Steps: 75, Sampler: DPM++ 2M SDE Karras, CFG scale: 6, Seed: 1068132009, Size: 512x680, Model hash: 84d76a0328, Model: epicrealism_naturalSinRC1VAE, ControlNet 0: "Module: ip-adapter_clip_sd15, Model: ip-adapter_sd15 [6a3f6166], Weight: 1, Resize Mode: Crop and Resize, Low Vram: False, Processor Res: 512, Guidance Start: 0, Guidance End: 1, Pixel Perfect: False, Control Mode: Balanced", Lora hashes: "epiCRealismHelper: c5e24d9bc4b5", TI hashes: "easynegative: c74b4e810b03", Version: v1.6.0-127-g102b6617
Template: beautiful eye closeup <lora:epiCRealismHelper:1>
Negative Template:  easynegative
```

a1111 expects the line with the comma-separated parameters to be the last line. In this case the Dynamic Prompts extension added more lines, which breaks the process.

Do you also use this extension? Does it work, if you remove it, generate a new image using controlnet and try again?

**Comment by siramods** [comment] 2023-10-01 18:30
Ok, so, I've tried to reproduce your prompt and my image info looks like this:
```
beautiful eye closeup <lora:epiCRealismHelper:1>

Negative prompt:  easynegative
Steps: 75, Sampler: DPM++ 2M SDE Karras, CFG scale: 6, Seed: 1068132009, Size: 512x680, Model hash: 84d76a0328, Model: epicrealism_naturalSinRC1VAE, ControlNet 0: "Module: ip-adapter_clip_sd15, Model: ip-adapter_sd15 [6a3f6166], Weight: 1, Resize Mode: Crop and Resize, Low Vram: False, Processor Res: 512, Guidance Start: 0, Guidance End: 1, Pixel Perfect: False, Control Mode: Balanced", Lora hashes: "epiCRealismHelper: c5e24d9bc4b5", Version: v1.6.0
```
My list of extensions is rather minimal, I've recently made a clean reinstall with all but most important ones i used, and as u can see, my last line is just all the info, ControlNet included, and nothing behind it. Still nothing, not from your Send to txt2img, not from PNG info tab, not from JPG or PNG output. ControlNet still stays blank. But later I will try to temporarily uninstall every other extension that's not CN, and see if your supposition is real, although my first guess is not that, weird thou CN has code for it, its above my paygrade. To say this, I do remember is that by using an extension called Unprompted, they did add some more stuff at the end of the prompt info, like your "Template" and "Negative Template" lines, and the effect was the PNG info tab didn't even successfully restored normal prompt info, like the seed and all, apparently whatever Unprompted did was running havoc thru the restore settings mechanism. In any case, I'll get back to you later with any other findings, thank you for putting your time into this, much appreciated. Here are the extensions I use presently:
```

ControlNet	https://github.com/lllyasviel/ControlNet	main	ed85cd1e	2023-09-09 21:09:12	unknown
multidiffusion-upscaler-for-automatic1111	https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git	main	f9f8073e	2023-07-22 08:53:11	unknown
sd-webui-additional-networks	https://github.com/kohya-ss/sd-webui-additional-networks.git	main	e9f3d622	2023-05-23 14:31:15	unknown
sd-webui-animatediff	https://github.com/continue-revolution/sd-webui-animatediff	master	e06e2ede	2023-09-17 18:30:43	unknown
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet	main	e67e0177	2023-09-11 09:56:10	unknown
sd-webui-segment-anything	https://github.com/continue-revolution/sd-webui-segment-anything	master	c555c6d9	2023-09-15 02:45:07	unknown
stable-diffusion-webui-images-browser	https://github.com/AlUlkesh/stable-diffusion-webui-images-browser	main	9f95e6d4	2023-09-11 14:55:51	unknown
txt2img2img	https://github.com/ThereforeGames/txt2img2img	main	9e53f57f	2022-12-22 05:04:46	unknown
ultimate-upscale-for-automatic1111	https://github.com/Coyote-A/ultimate-upscale-for-automatic1111	master	728ffcec	2023-09-09 12:47:23	unknown
LDSR	built-in	None			
Lora	built-in	None			
ScuNET	built-in	None			
SwinIR	built-in	None			
canvas-zoom-and-pan	built-in	None			
extra-options-section	built-in	None			
mobile	built-in	None			
prompt-bracket-checker	built-in	None		
```

**Comment by AlUlkesh** [comment] 2023-10-02 05:49
I just noticed that your list shows controlnet twice, from two separate repositories:

```
ControlNet	https://github.com/lllyasviel/ControlNet	main	ed85cd1e	2023-09-09 21:09:12	unknown
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet	main	e67e0177	2023-09-11 09:56:10	unknown
```

I have only the one from Mikubill running.

**Comment by siramods** [comment] 2023-10-02 13:16
Ok, so, two days ago I've been looking at my chain while biking in a parking lot, and frontally hit a light post, and from the ground that felt less shameful somehow than being pointed out I have two ControlNets installed. I have removed the offending lllyasviel version, and test it again. _Still . not . working_. But, I can confirm **you were RIGHT** all along, it does function properly on other A1111 installations. I have gone to rundiffusion.com which I happen to occasionally use, their deployment is pretty similar, list of extensions down below. And from "PNG Info" tab I've been able to send and restore proper CN configurations both in txt2img and img2img. A little finnicky I might say, sometimes u have to send it twice until it catches on, but it does work just fine. So, yes, its a local problem we have, well just have to sort it out. I'll be investigating further, but somehow I trust your eyes more. 

IF_prompt_MKR	https://github.com/if-ai/IF_prompt_MKR.git	main	65ad9a9f	2023-09-08 12:47:01	unknown
adetailer	https://github.com/Bing-su/adetailer.git	main	a0b4c56e	2023-09-10 13:14:54	unknown
canvas-zoom	https://github.com/richrobber2/canvas-zoom.git	main	efba3a94	2023-09-06 03:11:55	unknown
deforum	https://github.com/deforum-art/sd-webui-deforum.git	automatic1111-webui	9f61b647	2023-09-11 12:17:17	unknown
multidiffusion-upscaler-for-automatic1111	https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git	main	f9f8073e	2023-07-22 06:53:11	unknown
sd-webui-agent-scheduler	https://github.com/ArtVentureX/sd-webui-agent-scheduler.git	main	097fe4e5	2023-09-11 14:22:42	unknown
sd-webui-animatediff	https://github.com/continue-revolution/sd-webui-animatediff	master	e5856d2a	2023-09-12 01:13:20	unknown
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	main	e67e0177	2023-09-11 07:56:10	unknown
sd-webui-inpaint-anything	https://github.com/Uminosachi/sd-webui-inpaint-anything.git	main	096f14ea	2023-09-12 13:41:20	unknown
sd-webui-regional-prompter	https://github.com/hako-mikan/sd-webui-regional-prompter.git	main	0b3ac220	2023-09-05 11:23:27	unknown
sd-webui-roop	https://github.com/s0md3v/sd-webui-roop.git	main	3176d477	2023-08-21 21:07:08	unknown
sd-webui-segment-anything	https://github.com/continue-revolution/sd-webui-segment-anything.git	master	d0492ac6	2023-08-31 13:37:05	unknown
sd_dreambooth_extension	https://github.com/d8ahazard/sd_dreambooth_extension.git	temp_checkout_branch	34690769	2023-09-05 22:27:20	unknown
ultimate-upscale-for-automatic1111	https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git	master	728ffcec	2023-09-09 10:47:23	unknown
LDSR	built-in	None			
Lora	built-in	None			
ScuNET	built-in	None			
SwinIR	built-in	None			
canvas-zoom-and-pan	built-in	None			
extra-options-section	built-in	None			
mobile	built-in	None			
prompt-bracket-checker	built-in	None

**Comment by AlUlkesh** [comment] 2023-10-02 14:36
At first I had no idea where you were going with your biking story... Thanks for the laugh 😄 

Since you had two controlnets installed, there's no telling how the settings have gotten mixed.

If you want to, you can post your `ui-config.json` and` config.json` and I can take a look at them.

**Comment by siramods** [comment] 2023-10-05 17:45
Only because you mentioned those two files I've just removed them, and they got recreated. Now it works.. I can import CN settings back into SD. Thank you!

**Comment by AlUlkesh** [comment] 2023-10-05 18:03
Oh, very cool. Good 😃

**Closed** 2023-12-14 14:44 UTC
Labels: bug, upstream
