### ISSUE TITLE
[Feature request] Option for browsing folders

### ISSUE THREAD

**Issue by Woisek** [AlUlkesh/stable-diffusion-webui-images-browser#5] opened 2023-01-26 10:48 UTC
This nice extension needs an folder option, IMHO.
I guess every one of us stores images in named folders. So it would only be logical to have an option to browse folders and _then_ the images.
It would help, if we could use the "other" tab for that. So, when entering a root folder in "Images directory", it then would auto populate the dropdown with the existing sub-folders, so that we can use it to jump into the folders. Of yourse, this list had to be stored somewhere and must not be gone after a reload.
Would this be doable?

**Comment by AlUlkesh** [comment] 2023-01-26 23:22
Well, I wouldn't want to remove the current functionality. People might use the dropdown to store favorite folders.

So perhaps a new dropdown, that does what you suggest.

The current dropdown values are stored in the extensions's folder as `path_recorder.txt`, so that could be extended or a new on e put there.

So, I think perhaps two buttons, one for the current "store folder" and one for "list sub-folders".

What do you think?

**Comment by Woisek** [comment] 2023-01-27 15:20
> Well, I wouldn't want to remove the current functionality. People might use the dropdown to store favorite folders.

OK ... strange, at first, nothing was stored in the dropdown after a reload. I noticed it, because it made no sense for me to have this only "per session". Now I see it's in fact stored. Great. With that, we are halfway where I wanted to be. :)

> So perhaps a new dropdown, that does what you suggest.

After the above finding, maybe it's not necessary.

> The current dropdown values are stored in the extensions's folder as `path_recorder.txt`, so that could be extended or a new one put there.

Yes, I found out now. Suggestion: the possibility to delete a path from the dropdown (instead going into the .txt file and delete it there). Maybe a delete icon on the right side of the entry ... ?

> So, I think perhaps two buttons, one for the current "store folder" and one for "list sub-folders".
> What do you think?

Yes, that would be a possibility to keep it clean. And please, an option to "auto populate" from a folder which has sub-folders.
Thanks! :)

**Comment by Luke-L** [comment] 2023-01-27 20:41
this already exists, here https://github.com/JasonHoku/sd_images_browser

**Comment by Woisek** [comment] 2023-01-27 22:11
> this already exists, here https://github.com/JasonHoku/sd_images_browser

Thanks for the link. But what exactly is the difference, or what "exists" in this repo?

**Comment by AlUlkesh** [comment] 2023-01-27 23:00
I looked at it, it seems to be almost the same fork as this one, with one pull request missing there.

That's always the danger when the main repo gets abandoned, that similar forks spring up and potentially go divergent paths.

**Comment by AlUlkesh** [comment] 2023-01-29 08:31
@Woisek This is the first version of the function. Can you try it out, when you get a chance?

**Comment by Woisek** [comment] 2023-01-29 10:25
@AlUlkesh 
Thanks for the update!
At first look, it looks promising. I may make some comments and suggestions on what I see right now:

**Design-wise:**
* I suggest to make the input fields of the path on top of each other, not side by side. Why?
The paths can become rather long (at least for me) and then it will be unreadable in the dropdowns.
Example path:
I:\_temp_workfolder\_AI_generated_images\stable_diffusion\1950s pin up style lady\dreamshaper_v3.3\ -- images here --
I:\_temp_workfolder\_AI_generated_images\stable_diffusion\A dream of a distant galaxy\model_n-a\ -- images here --
I:\_temp_workfolder\_AI_generated_images\stable_diffusion\A dream of a distant galaxy\protogen_infinity_prunded_(1.6GB)\ -- images here --
I:\_temp_workfolder\_AI_generated_images\stable_diffusion\A dream of a distant galaxy\v1-5-pruned-emaonly\ -- images here --
I:\_temp_workfolder\_AI_generated_images\stable_diffusion\A dream of a distant galaxy\v2-1_768-ema-pruned\ -- images here --
etc.

I can imagine, this will not be so different to other users with a "sorting tick". :)

* Because we can enter a page number manually, it would be nice if the "page index" would display the max pages of the current folder -> 1 / xx or the like, so we don't enter a number that don't exist.

* The "sort by" field could also need a rearrangement. Again, on top of each other, so that all radio boxes are side by side on top and the input for the keyword search beneath. Basicly, make the fieldset 100% and let the block with the input field slide down. This would close this ugly and unnecessary gap of "three rows left and 1 right" like it is right now and become only two lines. :)
Also, a ASC/DESC sorting would be nice.


**Function-wise:**
How I understand the workflow you implemented right now is as follows:
Enter a directory (folder) -> folder is stored
When this folder is selected, the subdirectories can be retrieved ("Get Subdirectories") and then selected.
"Add to saved directories" adds this selected sub-directory to the main list in "Saved directories".

This is already a huge improvement, but I would like to see a tiny functionallity more:
Saving folders with a folder depth. I know you had let it read it completely through before, now it would be helpful if it came back with a manual set limiter.

What does that mean?
When clicking "Add to saved directory", have an small input beside where we can enter the depth (0 or empty, 1, 2, 10, ...).

Why is this important?
Again my examples with model sub folders:
I:\_temp_workfolder\_AI_generated_images\stable_diffusion\A dream of a distant galaxy\ **model_n-a** \ -- images here --
I:\_temp_workfolder\_AI_generated_images\stable_diffusion\A dream of a distant galaxy\ **protogen_infinity_prunded_(1.6GB)** \ -- images here --
I:\_temp_workfolder\_AI_generated_images\stable_diffusion\A dream of a distant galaxy\ **v1-5-pruned-emaonly** \ -- images here --
I:\_temp_workfolder\_AI_generated_images\stable_diffusion\A dream of a distant galaxy\ **v2-1_768-ema-pruned** \ -- images here --

Right now, I would have to save four different locations for basicly the same "root" folder. This list could then get rather long quickly if someone tests all or at least many different models (like me ;) ).

But doing a save like:
I:\_temp_workfolder\_AI_generated_images\stable_diffusion\A dream of a distant galaxy\ **:1**
would mean: Display this folder plus 1 folder deeper.
The obvious advantage of this would be to just save only 1 folder location instead of 4 and still getting all images from the containing sub folders (depth limited).

:)
Sorry for this long post.

I hope I'm not to demanding, just want to help make it better for all of us. :)

Thanks for your great work!

**Comment by AlUlkesh** [comment] 2023-01-31 09:55
@Woisek Those are all good suggestions, thanks. Can you check if this new commit covers all?

**Comment by Woisek** [comment] 2023-01-31 13:57
@AlUlkesh 
That was fast! :D
And with perfect execution, I must say. Kudos to you, this looks now really good as far as I can tell.
This is nor really usable with many options.

So now, there are only QOL items left. ;)
* Adding a "delete all saved directories" button (right after the "remove from directories" button)
* Because it is too long and breaks to the next line making it look ugly: change the "Page Index (of x pages)" to "Page (of x)". With that change, there could be displayed up to "Page (of 999999)" without breaking into the next line. :)
* An option to sort the "Saved directories" in Asc/Desc. And additional, as an absolute bonus option, a cherry on top so to say, would be: Drag'N'Drop sorting. :)

Coming back to the "remove from directories" button: When I want to remove a directory, the field of "Saved directories" gets blank and shows "Error". Clicking on it reveals the dropdown and selecting again is working OK, but the previous selected directory that should be deleted is still there. Did restart several times, but that didn't change this behaviour/error. :/
Possibly a bug or a problem with the textfile ... ?

Otherwise, great work! Many thanks again! .thumbsup.

**Comment by AlUlkesh** [comment] 2023-01-31 15:32
Thanks.

Yes, apparently I tried to select the removed path in the dropdown... should be fixed now.

**Comment by Woisek** [comment] 2023-01-31 15:48
Can confirm that deletion is now working. :) I love it!

**Comment by Woisek** [comment] 2023-02-02 10:07
Small addon:
I noticed right now, that allthough everything is working in the "Others" tab, this setting doesn't apply to the other tabs (txt2img, img2img, ..).
This folder structure that you perfectly build around is also used in thos folders to.
So, to make this also usable there, may I suggest to have a checkbox in those tabs, when checked, t reads all subfolders again like you had in the first place. That would be cool.

Thanks for your great work. :)

**Comment by AlUlkesh** [comment] 2023-02-02 10:10
Hmm... do you perhaps mean this setting in Settings?

![image](https://user-images.githubusercontent.com/99896447/216295906-54823308-5cfc-40b5-93fb-9820f6646d2d.png)

**Comment by Woisek** [comment] 2023-02-02 11:24
Woha ... sorry, I totally missed that ... &)
OK, this will work, thanks.

**Comment by AlUlkesh** [comment] 2023-02-02 22:59
Nah, if there's one thing missing in this extension, it's documentation. It's certainly less than intuitive in some places.

**Comment by Woisek** [comment] 2023-02-03 09:49
On the other hand, it's not so complex that you wouldn't understand it after 5 minutes of study. IMHO. :)

**Comment by Woisek** [comment] 2023-02-04 00:26
OK, sorry to say, but I have found something weird in the way the image browser handles files.
While the "Others" section works perfect, the other (lol) sections act weird:
Image browser copies images into my OS temp folder and shows them from there.
I wondered lately why my temp folder is always so cluttered with SD images ... obviously I found the culprit.

Before going into detail, could you please tell me, into what directory the "Favorite" tab points? It's strange, because there are most of those images found. And they are somehow coming from "inside WebUI", so to say. Images from extensions like "stable-diffusion-webui-artists-to-study" where also a lot of images are found.
But the most weird and annoying thing is, that image browser copys all those images to the system temp folder. The path it shows is the right one, but in fact it is a different one plus with altered filename.

Example:
Image browser shows in "filename": 
.\outputs\txt2img-images\100mm photo of isometric floating island in the sky surreal\Elldreth_elldreths_og_4060_mix_v1.0\00000-S.3681887791-St.30-Sa.Euler a-Cfg.10-M.Elldreth_elldreths_og_4060_mix_v1.0.png

But the actually file used and displyed is:
T:/systemp/00000-S7f349423427c29b7fe3082028c8cc07729c4ceda.3681887791-St.30-Sa.Euler a-Cfg.10-M.Elldreth_elldreths_og_4060_mix_v1.0.png

Take notice of the differend filename.
So ... what is happening here? :)

**Comment by AlUlkesh** [comment] 2023-02-04 10:11
Interesting. I can look into this more later, but for now some things you can check:

- Folder for "Favorite": From memory I think this is the one in general settings called "Directory for saving images using the Save button"
- Check these settings for the temp files:
  - Directory for temporary images
  - Cleanup non-default temporary directory when starting webui

I suspect this is something gradio does internally, so there probably is no way to influence it.

**Comment by Woisek** [comment] 2023-02-04 12:04
> Interesting. I can look into this more later, but for now some things you can check:
> 
>     Folder for "Favorite": From memory I think this is the one in general settings called "Directory for saving images using the Save button"
This is now empty. I had it set before, but now nothing is entered. Maybe that's why it points now to webui root somehow I guess ... ?

>     Check these settings for the temp files:
>     Directory for temporary images

Is set to T:\systemp\sd_temp_files
But nothing is saved there by now.

>       * Cleanup non-default temporary directory when starting webui
Is activated.

> I suspect this is something gradio does internally, so there probably is no way to influence it.

That would be a very strange behaviour of Gradio ... :/

I don't know, how the image browser actually works, but what I did right now, is the following:
I empty my temp folder, nothing in there.
I generate some images, they are saved in the defined folders as they should. The temp folder stays empty.
I send one image to img2img, save the new generated image and it's saved as expected. The temp folder stays empty.
I select the image browser tab, the gallery view of pre-selected txt2img is empty.
As soon I click on "First page", it displays the images from the given folder AND instantly it populates the temp folder with them. But to make it even more weird, not all of them.

I have 50 generated images in the txt2img folder (plus 1 generated txt for each image), image browser says "53 images in this directory, divided into 2 pages" and in my temp folder are 37 of the images copied.

So ... are there now any infos you can work with? :D

**Comment by AlUlkesh** [comment] 2023-02-05 06:22
I'm pretty sure it's gradio.

If you look at the code starting here:
https://github.com/gradio-app/gradio/blob/faffddf8c7c95348c83cc165a3c07e691a7e0196/gradio/processing_utils.py#L357

and your example:
00000-S.3681887791-St.30-Sa.Euler a-Cfg.10-M.Elldreth_elldreths_og_4060_mix_v1.0.png
-> 
00000-S7f349423427c29b7fe3082028c8cc07729c4ceda.3681887791-St.30-Sa.Euler a-Cfg.10-M.Elldreth_elldreths_og_4060_mix_v1.0.png

It takes everything up to the first dot as "prefix" and the rest as "extension". Then it creates a hash of the complete filename and inserts that between "prefix" and "extension".

I guess they didn't expect a filename to have more than one dot...

**Comment by Woisek** [comment] 2023-02-05 11:06
OK, so a test with another name convention on my side would be worth a try I guess ... ?!
But how does that explain the (completely unnecessary) copying to the system temp folder? If that's somehow related.
BTW, even if the displayed images are from the temp folder, if I delete one from the images browser, it deletes the original, but leaves the one in the temp folder alone.
Don't know if that info helps.

**Comment by AlUlkesh** [comment] 2023-02-05 14:35
Not much I can do about that I think, if gradio is the cause. I found this discussion about the behaviour:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/3278

**Comment by Woisek** [comment] 2023-02-05 15:05
Allright, I will watch this thread. Seems like this issue is not new and still not fixed. :/

BTW, I noticed the new "ranking" on the left and "ranking filter" on the right. Could you please quickly explain what it does? Because right now, I'm not sure how (or if) this works. For me, it does nothing right now (or I'm to dumb to get it &) ).

And another feature wish: When deleting one or more files from the browser, could we have a checkbox that activates the deletion of the matching generated .txt files with them? Would be awesome. :)

**Comment by AlUlkesh** [comment] 2023-02-05 16:16
The ranking is a manual ranking. Whenever there's a filename in the bottom right "File Name" field, pressing a ranking number saves this number into the image's exif-info. You can then later filter by rank.

Sure, I'll put the txt-delete in one of the next version.

**Comment by Woisek** [comment] 2023-02-05 17:32
> The ranking is a manual ranking. Whenever there's a filename in the bottom right "File Name" field, pressing a ranking number saves this number into the image's exif-info. You can then later filter by rank.

OK, then something is not right here, I'm doing something probably wrong.

I open the browser, txt2img. Click "First page" to get the images populated.
I select an image and click some number under "ranking". The image should be now ranked with that number, right?
When I now click on the same number under "ranking filter", nothing shows up, all blank/empty. That's not how it should be, I suppose.

Where is my error?

> Sure, I'll put the txt-delete in one of the next version.

Great news! Thanks! :D

**Comment by AlUlkesh** [comment] 2023-02-05 17:59
I misremembered. The ranking is not saved in the exif, but in its own file in the extension directory as ranking.json. Do you have that?

**Comment by Woisek** [comment] 2023-02-05 19:42
> I misremembered. The ranking is not saved in the exif, but in its own file in the extension directory as ranking.json. Do you have that?

`{"I:\\stable_diffusion_shared\\outputs\\txt2img-images\\porait of a man by Greg Rutkowski he is about\\SD v1.5_v1-5-pruned-emaonly_(3.97GB)\\00003-S=2879552929-St=20-Sa=Euler a-Cfg=7-M=SD v1.5_v1-5-pruned-emaonly_(3.97GB).png": "5", "I:\\stable_diffusion_shared\\outputs\\txt2img-images\\porait of a man by Greg Rutkowski he is about\\SD v1.5_v1-5-pruned-emaonly_(3.97GB)\\00000-S=3628946550-St=20-Sa=Euler a-Cfg=7-M=SD v1.5_v1-5-pruned-emaonly_(3.97GB).png": "1"}`

The file exists, but it seems it's not being applied/used ... ?!

**Comment by AlUlkesh** [comment] 2023-02-05 21:15
Yes, that was a bug, that snuck in there in one of the last versions. Should be fixed now.

**Comment by Woisek** [comment] 2023-02-05 21:42
Yes, can confirm that it is now working. Thanks! :D

**Comment by AlUlkesh** [comment] 2023-02-08 09:12
This should now handle the matching txt-files, if set:
![image](https://user-images.githubusercontent.com/99896447/217485663-a2c43b00-1235-43ce-8605-9fa1b0b63ded.png)

**Comment by AlUlkesh** [comment] 2023-02-10 00:04
Interesting, there is loads of room on my end:
![image](https://user-images.githubusercontent.com/99896447/217966720-5e87d7b7-f5f3-4056-b045-ccd73e6ccea6.png)

Are you working with a very small window?

**Comment by Woisek** [comment] 2023-02-10 09:44
> Are you working with a very small window?

Nope, it's FullHD (1920), but I use a custom skin from this repo -> https://github.com/Gerschel/sd-web-ui-quickcss but I doubt that this makes such a differens for the label definition. Even if I make the font smaller, it has to be WAY smaller to fit into one line.

I attached a screenshot. I noticed that overlap also with "Include negative prompt in exif search". And, nagging at a high level, maybe we can get the buttons in line with the "sort by" box? If you have any access to styling of course ...

![Screenshot 2023-02-10 at 10-34-11 Stable Diffusion](https://user-images.githubusercontent.com/122026301/218058256-4a55e151-aa91-458c-8aac-d5f4647d9126.jpg)

**Comment by Woisek** [comment] 2023-02-10 10:24
While I'm on it, I noticed something odd again:
When browsing the gallery and you use the "delete next" option and enter, say 2, and hit delete, it deletes the two images.
BUT: If you then use the arrow keys to navigate left and right, it displays the two deleted images, altough there are _not_ visible in the image bar on the bottom. If one then hits delete again on a supposed to be deleted image again, it deletes the next one.
This is potential dangerous, as one could delete images that shouldn't or wanted to be deleted.

I hope I explained it well.

**Comment by AlUlkesh** [comment] 2023-02-10 14:08
Well. I'd say this is a problem with the css used in that extension. There is no problem on default, even if I make the window smaller:
![image](https://user-images.githubusercontent.com/99896447/218110639-6bdf0d34-d9a0-4e08-b10a-72b52145652f.png)


However, since it's such a small change I shortened the two texts: https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/7a7c97b76aa531f26ebbd95f04a3926faf8e46b8

**Comment by Woisek** [comment] 2023-02-10 22:43
> Hmm... do you perhaps mean this setting in Settings?
> 
> ![image](https://user-images.githubusercontent.com/99896447/216295906-54823308-5cfc-40b5-93fb-9820f6646d2d.png)

I noticed, that this option also affects the "Other" tab. But when activated, the sub folder index has no effect. Meaning an index of 0 will show images in the subdirectory anyway.
Any chance to exclude the checkbox function for the "Others" tab?

**Comment by Woisek** [comment] 2023-02-10 22:47
> Well. I'd say this is a problem with the css used in that extension. There is no problem on default, even if I make the window smaller: ![image](https://user-images.githubusercontent.com/99896447/218110639-6bdf0d34-d9a0-4e08-b10a-72b52145652f.png)
> 
> However, since it's such a small change I shortened the two texts: [7a7c97b](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/7a7c97b76aa531f26ebbd95f04a3926faf8e46b8)

Yes, I deactivated it and reverted to the light theme and it fits now.
Ich will check the style again. Thanks.

**Comment by AlUlkesh** [comment] 2023-02-10 23:05
> Any chance to exclude the checkbox function for the "Others" tab?

That was the intention... should be fixed now.

**Comment by Woisek** [comment] 2023-02-10 23:15
Perfect! It's working now ... 👍

**Comment by Woisek** [comment] 2023-02-12 18:01
OK, raised another wish. :)
"Move to favorites" (wherever this may be) is nice. But it would be better to define the destination for our selfes. :)

Could we get a "Move to folder" button, where we can specify the folder where it should be moved (not copied!)? Ideally so, that the target directory will be created if it not exists.
Maybe underneath "Send to extras", like in the mockup I attached:

![Zwischenablagebild](https://user-images.githubusercontent.com/122026301/218328464-42d0c2bd-f235-47ca-999e-eccab020930f.png)

Thanks.

**Closed** 2023-02-23 21:54 UTC
Labels: enhancement
