### ISSUE TITLE
The cur_path always using default path under SD installation path

### ISSUE THREAD

**Issue by timerho** [AlUlkesh/stable-diffusion-webui-images-browser#187] opened 2023-05-29 05:08 UTC
The store path of txt2img has changed to "D:\stable-diffusion-webui\outputs\txt2img-images, but debug message show it still using the default path and can not browse any images.

Startup time: 5.3s (list SD models: 0.3s, load scripts: 3.2s, create ui: 1.5s, gradio launch: 0.2s).
2023-05-29-12:50:02 image_browser.py: get_image_page
2023-05-29-12:50:02 image_browser.py: get_all_images
2023-05-29-12:50:02 image_browser.py: curr_path: C:\stable-diffusion-webui\outputs\txt2img-images
2023-05-29-12:50:02 image_browser.py: cache_exif: 0/0 cache_aes: 0/0 0.0 seconds

**Comment by AlUlkesh** [comment] 2023-05-29 22:02
What does it say at this point in the debug output?

`["Name: txt2img / Path: C:\\tools\\Ai\\tests\\stable-diffusion-webui-20230526\\outputs\\txt2img-images / Base tag: image_browser_tab_txt2img / Seen base tags: {'img2img', 'maintenance',` ...

**Comment by timerho** [comment] 2023-05-30 02:21
> What does it say at this point in the debug output?
> 
> `["Name: txt2img / Path: C:\\tools\\Ai\\tests\\stable-diffusion-webui-20230526\\outputs\\txt2img-images / Base tag: image_browser_tab_txt2img / Seen base tags: {'img2img', 'maintenance',` ...
Please refer to attached log below, this issue happened after I upgrade to SD 1.3.0. The current workaround is to use the mklink command to redirect the directory to the output directory.
2023-05-30-10:08:51 image_browser.py: ["Name: txt2img / Path: D:\\stable-diffusion-webui\\outputs\\txt2img-images / Base tag: image_browser_tab_txt2img / Seen base tags: {'img2img', 'maintenance', 'txt2img-grids', 'img2img-grids', 'txt2img', 'favorites', 'extras', 'others'}", "Name: img2img / Path: D:\\stable-diffusion-webui\\outputs\\img2img-images / Base tag: image_browser_tab_img2img / Seen base tags: {'img2img', 'maintenance', 'txt2img-grids', 'img2img-grids', 'txt2img', 'favorites', 'extras', 'others'}", "Name: txt2img-grids / Path: D:\\stable-diffusion-webui\\outputs\\txt2img-grids / Base tag: image_browser_tab_txt2img-grids / Seen base tags: {'img2img', 'maintenance', 'txt2img-grids', 'img2img-grids', 'txt2img', 'favorites', 'extras', 'others'}", "Name: img2img-grids / Path: D:\\stable-diffusion-webui\\outputs\\img2img-grids / Base tag: image_browser_tab_img2img-grids / Seen base tags: {'img2img', 'maintenance', 'txt2img-grids', 'img2img-grids', 'txt2img', 'favorites', 'extras', 'others'}", "Name: Extras / Path: D:\\stable-diffusion-webui\\outputs\\extras-images / Base tag: image_browser_tab_extras / Seen base tags: {'img2img', 'maintenance', 'txt2img-grids', 'img2img-grids', 'txt2img', 'favorites', 'extras', 'others'}", "Name: Favorites / Path: D:\\stable-diffusion-webui\\log\\images / Base tag: image_browser_tab_favorites / Seen base tags: {'img2img', 'maintenance', 'txt2img-grids', 'img2img-grids', 'txt2img', 'favorites', 'extras', 'others'}", "Name: Others / Path: C:\\stable-diffusion-webui\\Others / Base tag: image_browser_tab_others / Seen base tags: {'img2img', 'maintenance', 'txt2img-grids', 'img2img-grids', 'txt2img', 'favorites', 'extras', 'others'}", "Name: Maintenance / Path: C:\\stable-diffusion-webui\\Maintenance / Base tag: image_browser_tab_maintenance / Seen base tags: {'img2img', 'maintenance', 'txt2img-grids', 'img2img-grids', 'txt2img', 'favorites', 'extras', 'others'}"]
[image_browser.log](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/files/11595104/image_browser.log)

**Comment by AlUlkesh** [comment] 2023-05-31 00:12
Ok, thanks. Yes, that's apparently also caused by a new functionality in webui. The first thing was already fixed here: #181

Once I'm back, at the end of the week, I'll look into more detail into this webui change.

**Comment by AlUlkesh** [comment] 2023-06-03 09:40
See #195

**Comment by AlUlkesh** [comment] 2023-06-04 23:38
@timerho 
I just merged the fix for #195. Can you check if it also fixes this issue?

**Comment by timerho** [comment] 2023-06-05 12:44
> @timerho I just merged the fix for #195. Can you check if it also fixes this issue?

I try this merge with latest SSD 1.3.2 and it's work. I can browser images in specific folder.

**Comment by AlUlkesh** [comment] 2023-06-05 22:10
Great! Thanks.

**Closed by AlUlkesh** 2023-06-05 22:10 UTC
Labels: bug, upstream
